version: "3.8"

services:
  mysql_db:
    image: mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    env_file:
      - ./server/.env
    volumes:
      - dbdata:/var/lib/mysql

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
      target: dev
    depends_on:
      - mysql_db
    ports:
      - 4000:4000
    env_file:
      - ./server/.env
    volumes:
      - ./server:/home/node/app
      - ${VIDEOS_PATH}:/mnt/videos:ro
      - server_cache:/data/.cache

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      target: dev
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    volumes:
      - ./client:/home/node/app

volumes:
  dbdata:
  server_cache:
