version: "3.8"

services:
  mysql_db:
    image: mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    env_file:
      - ./server/.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build:
      dockerfile: Dockerfile
      context: ./server
      target: dev
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - 4000:4000
    env_file:
      - ./server/.env
    volumes:
      - ./server:/home/node/app
      - ignore_api:/home/node/app/node_modules/
      - ${VIDEOS_PATH}:/mnt/videos:ro
      - server_cache:/data/.cache

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      target: dev
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    volumes:
      - ./client:/home/node/app
      - ignore_client:/home/node/app/node_modules/

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3050:80

volumes:
  dbdata:
  server_cache:
  ignore_api:
  ignore_client:
